version: "3.7"

services:
  mongodb:
    image : mongo
    container_name: mongodb_container
    volumes:
    - mongodb-data:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  apis:
    build: ./backend
    container_name: apis_container
    environment:
      - MONGO_HOST=mongodb
    ports:
      - 5000:5000
    restart: unless-stopped
  charts:
    image: quay.io/mongodb/charts:v1.20.2
    ports:
      - 9999:80
    environment:
      CHARTS_SUPPORT_WIDGET_AND_METRICS: 'on'
      SSL_CERT_DIR: /mongodb-charts/volumes/db-certs
      CHARTS_MONGODB_URI: 'mongodb://mongodb:27017'
    volumes:
      - keys:/mongodb-charts/volumes/keys
      - logs:/mongodb-charts/volumes/logs
      - db-certs:/mongodb-charts/volumes/db-certs
      - web-certs:/mongodb-charts/volumes/web-certs
    container_name: charts_container
    depends_on: 
      - mongodb
  # node-red:
  #   image: nodered/node-red:latest
  #   container_name: nodered_container
  #   environment:
  #     - TZ=Europe/Amsterdam
  #   ports:
  #     - "1880:1880"
  #   volumes:
  #     - ./node-red:/data
  #   restart: unless-stopped
volumes:
  mongodb-data:
  keys:
  logs:
  db-certs:
  web-certs:
