version: "3.7"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file: ./postgres.env
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  apis:
    build: ./backend
    container_name: apis_container
    ports:
      - 5000:5000 # apis port
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/root/.pgadmin

    ports:
      - "5050:80"
    restart: unless-stopped
  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana_container
    volumes:
      - ./grafana/etc:/etc/grafana
      - ./grafana/lib:/var/lib/grafana
      - ./grafana/log:/var/log/grafana
    ports:
      - 4000:3000
    env_file: ./grafana/grafana.env
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    restart: unless-stopped
volumes:
  postgres-data:
  pgadmin:
