version: "3.7"

services:
  mongodb:
    image : mongo
    container_name: mongodb_container
    volumes:
    - mongodb-data:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  apis:
    build: ./backend
    container_name: apis_container
    environment:
      - MONGO_HOST=mongodb
    ports:
      - 5000:5000 # apis port
    restart: unless-stopped
  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana_container
    volumes:
      - ./grafana/etc:/etc/grafana
      - ./grafana/lib:/var/lib/grafana
      - ./grafana/log:/var/log/grafana
    ports:
      - 8080:3000
    env_file: ./grafana/grafana.env
    depends_on: 
      - mongodb
  node-red:
    image: nodered/node-red:latest
    container_name: nodered_container
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    restart: unless-stopped
volumes:
  mongodb-data:
